### ISSUE TITLE
Expose motor encoder values via SDK

### ISSUE THREAD

**Issue by avirtuos** [sphero-inc/sphero-sdk-raspberrypi-python#7]
I tried to find if there was a way to read the motor encoder values but was unable to find a way to do so. Can you point me in the right direction or consider this as a feature request to expose the encoder values. This is extremely useful for using RVR with basic SLAM or dead-reconning algorithms that depend on or can be enhanced by odometry.

**Comment by acampos81** [comment]
Hello @avirtuos, I apologize for the delay in responding.  We've been super slammed lately.  As of right now we do not expose the motor encoder values in our public SDK, but are considering making it available with our next firmware release.   Would a 32-bit signed tick accumulator for each encoder be suitable data for SLAM usage?

**Comment by avirtuos** [comment]
Yea that should work.

**Comment by cletusw** [comment]
Looks like this should be closed due to [this summer's firmware update](https://support.sphero.com/article/q72m8y88a4-important-rvr-firmware-update#encoders)?

[Code](https://github.com/sphero-inc/sphero-sdk-raspberrypi-python/blob/74599f351cacb3fcaa03d3ba41e706cba3c5ab95/sphero_sdk/observer/client/toys/sphero_rvr_observer.py#L1067-L1079)

**Comment by Jim-Konish** [comment]
Yes, this is covered by the August 2020 firmware/SDK update.
